---
title: "STAT340_project"
date: "12/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(maps)
library(mapdata)
library(usdata)
```

## R Markdown

```{r load the data}
data <- read.csv("Levels_Fyi_Salary_Data.csv")
head(data)
```


```{r}
# filter gender, drop NA and other in gender
filted_data <- data %>%
  filter(gender %in% c("Female", "Male"))
filted_data %>%
        group_by(gender) %>%
        summarise(n= n())


```
```{r}
# modify location column, drop location outside US and leave only state information
filted_data = filted_data %>%
  select(company, level, title, totalyearlycompensation, location, yearsofexperience, yearsatcompany, basesalary,
         stockgrantvalue, bonus, gender, Race, Education) %>% 
  group_by(location) %>% 
  mutate(new_location = strsplit(location, ', ')[[1]][2])



states <- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY")

filted_data <- filted_data %>% 
  filter(new_location %in% states)

head(filted_data)

```

```{r}
filted_data1 <- filted_data %>% 
  filter(!is.na(Race))
ggplot(filted_data1, aes(x = Race, y = basesalary, fill = gender)) +
  geom_boxplot()+ggtitle("Relationship between gender, race and basesalary")+ylab("Basesalary")
```

```{r}
ggplot(filted_data) +
  geom_boxplot(aes(x=as.character(new_location),y=basesalary, fill=new_location),
                outlier.shape = NA,alpha= 0.3) +
  theme(legend.position="none") +
  ylim(0, 260000) +
  ylab("base salary") +
  xlab("States") +
  scale_x_discrete(guide = guide_axis(angle = 60)) +
  ggtitle("Base Salary in Different State")
```

```{r}
state_mean=filted_data %>%
  group_by(new_location) %>%
  summarise(n= n(),
            mean_salary_state=mean(basesalary))
 
ggplot(state_mean, aes(x=reorder(new_location, mean_salary_state),y=mean_salary_state)) +
  geom_point() + 
  geom_line() +
  scale_x_discrete(guide = guide_axis(angle = 60)) +
  ylab("Average Base Salary") +
  xlab("States") +
  ggtitle("Average Base Salary of each States")
```

```{r}

library(lubridate)
states <- map_data("state") %>% 
  select(-subregion) %>% 
  mutate(new_location = state2abbr(region))

states = full_join(states, state_mean, by = "new_location") 

ggplot(states, aes(x = long, y = lat, group = group, fill = mean_salary_state)) +
  geom_polygon(color = "white") +
  coord_fixed(1.5) +
  theme_bw()+ ggtitle("Average Base Salary for different US States") + 
  xlab("Longitude")+ 
  ylab("Latitude")+
  labs(caption = "Tips: No data for SD(South Dakota)")+
  scale_fill_continuous(name="Average Base Salary", 
            low = "lightblue", high = "darkblue",limits = c(60000,180000), 
            breaks=c(60000,80000,100000,120000,140000,160000), na.value = "grey50")

```
```{r}
filted_data %>% 
  ggplot(aes(x = gender, y = log(basesalary), fill = gender)) +
  geom_boxplot()+ggtitle("Relationship between gender and basesalary")+ylab("Basesalary")
```
```{r}
ggplot(filted_data) + 
  geom_density(aes(x = log(basesalary), color = gender), alpha = 0.2) +
  xlab('Base Salary') +
  ylab('Density') +
  ggtitle('Density of Base Salary')
```
```{r}
# using wilcoxon test to test whether the median income of the male and female
res <- wilcox.test(basesalary ~ gender, filted_data,var.equal = TRUE)
res
```
```{r}
# We'll adapt the permutation testing approach we saw in lecture.
# Each MC replicate, we will randomly assign the data to two groups and compare their me ans.
# Then we'll see how the true difference in means compares to these.
male_data <- filted_data %>% 
  filter(gender == "Male")
female_data <- filted_data %>% 
  filter(gender == "Female")
Nrep <- 1000; 
reps <- rep( NA, Nrep)
n <- nrow(filted_data);

n_male <- nrow(male_data)
n_female <- nrow(female_data)

for( i in 1:Nrep ) {
  inds <- sample(1:n, n_male, replace=FALSE );
  reps[i] <- median(filted_data[inds,]$basesalary) - mean(filted_data[-inds,]$basesalary)
  }
# Form the CI
CI <- as.vector( quantile(reps, probs = c(0.025,0.975)) );
# Note that we could get these means with a more graceful GroupBy operation,
# But I want to make it very clear what we are computing here. 
Female_inds <- (filted_data$gender== "Female");
Female_salary <- filted_data[Female_inds,]$basesalary;
Female_median <- median(Female_salary);
Male_inds <- (filted_data$gender== "Male");
Male_salary <- filted_data[Male_inds,]$basesalary;
Male_median <- median(Male_salary);
popdiff <- Female_median-Male_median;

(CI[1] < popdiff) & (popdiff < CI[2]);
```
```{r}
mlm <- lm(basesalary ~ 1+yearsofexperience+yearsatcompany+title+new_location,male_data)
summary(mlm)
flm <- lm(basesalary ~ 1+yearsofexperience+yearsatcompany+title+new_location,female_data)
summary(flm)
```